#!/usr/bin/env python3
"""Remove entity entries that name a set of things rather than one thing.

A reader who cannot establish which benchmark a paper used is asked to leave
`datasets` empty. Writing "three mathematical reasoning benchmarks (unnamed in
abstract)" instead reads as harmless caution and is not, because
`publish/wiki.py` keys wiki entities by their string. Two unrelated papers that
phrase their placeholder identically merge into one entity, count each other as
independent evidence, and cross the promotion threshold as a concept that does
not exist. That happened here: "five reasoning benchmarks (unnamed in
abstract)" reached two sources from FoE and SeLaR — different benchmark sets —
and was queued for a definition.

`queue.validate_result` now rejects these at submission, so this script exists
for summaries already stored. It shares the detector with the validator rather
than reimplementing it, so the two cannot drift.

    python3 scripts/strip_placeholder_entities.py            # dry run
    python3 scripts/strip_placeholder_entities.py --apply

Only the four harvested fields are touched — `concepts`, `methods`, `datasets`,
`models`. Prose fields are left alone: "three mathematical reasoning benchmarks
(unnamed in abstract)" is a true and useful sentence inside `results`, and only
becomes a problem when it is offered as a name.

Stripping an entry can drop an entity below the promotion threshold. Wiki notes
are regenerated by `pipelines.render`, which removes notes whose evidence is
gone, so run a render afterwards; anything a reader wrote after an
`<!-- auto:end -->` marker is preserved as always.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipelines.common import config as config_mod  # noqa: E402
from pipelines.common.store import read_json, write_json  # noqa: E402
from pipelines.local.placeholders import looks_like_placeholder  # noqa: E402

_FIELDS = ("concepts", "methods", "datasets", "models")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply", action="store_true", help="write changes (default is a dry run)"
    )
    args = parser.parse_args()

    cfg = config_mod.load()
    roots = [
        cfg.layout.summaries / "papers",
        cfg.layout.summaries / "videos",
    ]

    touched = 0
    removed = 0
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.glob("*.json")):
            data = read_json(path)
            if not isinstance(data, dict):
                continue
            changes: list[tuple[str, str]] = []
            for field in _FIELDS:
                values = data.get(field)
                if not isinstance(values, list):
                    continue
                kept = []
                for entry in values:
                    if isinstance(entry, str) and looks_like_placeholder(entry):
                        changes.append((field, entry))
                    else:
                        kept.append(entry)
                if len(kept) != len(values):
                    data[field] = kept
            if not changes:
                continue
            touched += 1
            removed += len(changes)
            print(f"{path.name}")
            for field, entry in changes:
                print(f"    - {field}: {entry}")
            if args.apply:
                write_json(path, data)

    if not touched:
        print("no placeholder entries found")
        return 0

    if not args.apply:
        print(
            f"\n{removed} entry(ies) in {touched} summary(ies) would be removed. "
            "Re-run with --apply."
        )
        return 0

    print(f"\nremoved {removed} entry(ies) from {touched} summary(ies)")
    print("run `python3 -m pipelines.render` to rebuild the wiki")
    return 0


if __name__ == "__main__":
    sys.exit(main())
